################### smother ##############################
# Seasonality
plot([alpha_hat[i][3] for i in 14:length(alpha_hat)], label = "Seasonality(1)",legend=:bottomright)
plot!([alpha_hat[i][3] + sqrt(V_true[i][3,3])*1.96 for i in 14:length(alpha_hat)], label = "Seasonality(1) + 1.96*dp")
plot!([alpha_hat[i][3] - sqrt(V_true[i][3,3])*1.96 for i in 14:length(alpha_hat)], label = "Seasonality(1) - 1.96*dp")
savefig("figs\\season_1_smother_$(s).png")
plot([alpha_hat[i][5] for i in 14:length(alpha_hat)], label = "Seasonality(2)",legend=:bottomright)
plot!([alpha_hat[i][5] + sqrt(V_true[i][5,5])*1.96 for i in 14:length(alpha_hat)], label = "Seasonality(2) + 1.96*dp")
plot!([alpha_hat[i][5] - sqrt(V_true[i][5,5])*1.96 for i in 14:length(alpha_hat)], label = "Seasonality(2) - 1.96*dp")
savefig("figs\\season_2_smother_$(s).png")
plot([alpha_hat[i][7] for i in 14:length(alpha_hat)], label = "Seasonality(3)",legend=:bottomright)
plot!([alpha_hat[i][7] + sqrt(V_true[i][7,7])*1.96 for i in 14:length(alpha_hat)], label = "Seasonality(3) + 1.96*dp")
plot!([alpha_hat[i][7] - sqrt(V_true[i][7,7])*1.96 for i in 14:length(alpha_hat)], label = "Seasonality(3) - 1.96*dp")
savefig("figs\\season_3_smother_$(s).png")
plot([alpha_hat[i][9] for i in 14:length(alpha_hat)], label = "Seasonality(4)",legend=:bottomright)
plot!([alpha_hat[i][9] + sqrt(V_true[i][9,9])*1.96 for i in 14:length(alpha_hat)], label = "Seasonality(4) + 1.96*dp")
plot!([alpha_hat[i][9] - sqrt(V_true[i][9,9])*1.96 for i in 14:length(alpha_hat)], label = "Seasonality(4) - 1.96*dp")
savefig("figs\\season_4_smother_$(s).png")
plot([alpha_hat[i][11] for i in 14:length(alpha_hat)], label = "Seasonality(5)",legend=:bottomright)
plot!([alpha_hat[i][11] + sqrt(V_true[i][11,11])*1.96 for i in 14:length(alpha_hat)], label = "Seasonality(5) + 1.96*dp")
plot!([alpha_hat[i][11] - sqrt(V_true[i][11,11])*1.96 for i in 14:length(alpha_hat)], label = "Seasonality(5) - 1.96*dp")
savefig("figs\\season_5_smother_$(s).png")
plot([alpha_hat[i][13] for i in 14:length(alpha_hat)], label = "Seasonality(6)",legend=:bottomright)
plot!([alpha_hat[i][13] + sqrt(V_true[i][13,13])*1.96 for i in 14:length(alpha_hat)], label = "Seasonality(6) + 1.96*dp")
plot!([alpha_hat[i][13] - sqrt(V_true[i][13,13])*1.96 for i in 14:length(alpha_hat)], label = "Seasonality(6) - 1.96*dp")
savefig("figs\\season_6_smother_$(s).png")

# Level
plot([alpha_hat[i][1] for i in 14:length(alpha_hat)], label = "Level",legend=:bottomright)
plot!([alpha_hat[i][1] + sqrt(V_true[i][1,1])*1.96 for i in 14:length(alpha_hat)], label = "Level + 1.96*dp")
plot!([alpha_hat[i][1] - sqrt(V_true[i][1,1])*1.96 for i in 14:length(alpha_hat)], label = "Level - 1.96*dp")
savefig("figs\\level_smother_$(s).png")
# Slope
plot([alpha_hat[i][2] for i in 14:length(alpha_hat)], label = "Slope",legend=:bottomright)
plot!([alpha_hat[i][2] + sqrt(V_true[i][2,2])*1.96 for i in 14:length(alpha_hat)], label = "Slope + 1.96*dp")
plot!([alpha_hat[i][2] - sqrt(V_true[i][2,2])*1.96 for i in 14:length(alpha_hat)], label = "Slope - 1.96*dp")
savefig("figs\\slope_smother_$(s).png")



################### FK ##############################
plot([a[i][3] for i in 14:length(a)], label = "Seasonality(1)",legend=:bottomright)
plot!([a[i][3] + sqrt(P[i][3,3])*1.96 for i in 14:length(a)], label = "Seasonality(1) + 1.96*dp")
plot!([a[i][3] - sqrt(P[i][3,3])*1.96 for i in 14:length(a)], label = "Seasonality(1) - 1.96*dp")
savefig("figs\\season_1_FK_$(s).png")
plot([a[i][5] for i in 14:length(a)], label = "Seasonality(2)",legend=:bottomright)
plot!([a[i][5] + sqrt(P[i][5,5])*1.96 for i in 14:length(a)], label = "Seasonality(2) + 1.96*dp")
plot!([a[i][5] - sqrt(P[i][5,5])*1.96 for i in 14:length(a)], label = "Seasonality(2) - 1.96*dp")
savefig("figs\\season_2_FK_$(s).png")
plot([a[i][7] for i in 14:length(a)], label = "Seasonality(3)",legend=:bottomright)
plot!([a[i][7] + sqrt(P[i][7,7])*1.96 for i in 14:length(a)], label = "Seasonality(3) + 1.96*dp")
plot!([a[i][7] - sqrt(P[i][7,7])*1.96 for i in 14:length(a)], label = "Seasonality(3) - 1.96*dp")
savefig("figs\\season_3_FK_$(s).png")
plot([a[i][9] for i in 14:length(a)], label = "Seasonality(4)",legend=:bottomright)
plot!([a[i][9] + sqrt(P[i][9,9])*1.96 for i in 14:length(a)], label = "Seasonality(4) + 1.96*dp")
plot!([a[i][9] - sqrt(P[i][9,9])*1.96 for i in 14:length(a)], label = "Seasonality(4) - 1.96*dp")
savefig("figs\\season_4_FK_$(s).png")
plot([a[i][11] for i in 14:length(a)], label = "Seasonality(5)",legend=:bottomright)
plot!([a[i][11] + sqrt(P[i][11,11])*1.96 for i in 14:length(a)], label = "Seasonality(5) + 1.96*dp")
plot!([a[i][11] - sqrt(P[i][11,11])*1.96 for i in 14:length(a)], label = "Seasonality(5) - 1.96*dp")
savefig("figs\\season_5_FK_$(s).png")
plot([a[i][13] for i in 14:length(a)], label = "Seasonality(6)",legend=:bottomright)
plot!([a[i][13] + sqrt(P[i][13,13])*1.96 for i in 14:length(a)], label = "Seasonality(6) + 1.96*dp")
plot!([a[i][13] - sqrt(P[i][13,13])*1.96 for i in 14:length(a)], label = "Seasonality(6) - 1.96*dp")
savefig("figs\\season_6_FK_$(s).png")

# Level
plot([a[i][1] for i in 14:length(a)], label = "Level",legend=:bottomright)
plot!([a[i][1] + sqrt(P[i][1,1])*1.96 for i in 14:length(a)], label = "Level + 1.96*dp")
plot!([a[i][1] - sqrt(P[i][1,1])*1.96 for i in 14:length(a)], label = "Level - 1.96*dp")
savefig("figs\\level_FK_$(s).png")
# Slope
plot([a[i][2] for i in 14:length(a)], label = "Slope",legend=:bottomright)
plot!([a[i][2] + sqrt(P[i][2,2])*1.96 for i in 14:length(a)], label = "Slope + 1.96*dp")
plot!([a[i][2] - sqrt(P[i][2,2])*1.96 for i in 14:length(a)], label = "Slope - 1.96*dp")
savefig("figs\\slope_FK_$(s).png")