name = "Simplex"
uuid = "3216ebdf-165f-4d97-826b-bc9216555479"
authors = ["thiagonovaesb <thiagonovaes@psr-inc.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "LinearAlgebra", "Random"]
